app = 'stackspulse'
primary_region = 'sjc'

[build]
# Comment next line to deploy the app from source code
image = "ghcr.io/pradel/stackspulse:0.13.0"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
  [http_service.concurrency]
    type = "requests"
    soft_limit = 400
    hard_limit = 450

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
