import { Footer } from "@/components/Layout/Footer";
import { Header } from "@/components/Layout/Header";
import { Theme } from "@radix-ui/themes";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const font = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body
        suppressHydrationWarning
        className={`${font.variable} font-sans antialiased`}
      >
        <Theme appearance="dark" accentColor="orange" grayColor="sand">
          <Header />
          {children}
          <Footer />
        </Theme>
      </body>
    </html>
  );
}
