name: cron-weekly

on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * 0'

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: weekly-cron-job
        run: |
          curl --request GET \
          --url 'https://www.stackspulse.com/api/cron/weekly-users' \
          --header 'Authorization: Bearer ${{ secrets.CRON_API_TOKEN }}'
