name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Create Release Pull Request
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm run version
          publish: pnpm run release
          commit: 'chore: release'
          title: 'chore: create new release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger Docker Publish
        if: steps.changesets.outputs.published == 'true'
        run: gh workflow run docker-publish.yml --ref stackspulse@${{ fromJson(steps.changesets.outputs.publishedPackages)[0].version }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
